name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.3
        with:
            ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install python requirements
        run: pip install -r requirements.txt
      - name: Execute the build
        run: ./.github/build.sh
        env:
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
